#pragma once

#define EDITOR_VERSION_MAJOR 0
#define EDITOR_VERSION_MINOR 1
#define EDITOR_VERSION_PATCH 7

#define EDITOR_BUILD_NUMBER 94
#define EDITOR_BUILD_BRANCH_OFFSET 30
#define EDITOR_GIT_HASH "a7d5e13"
#define EDITOR_GIT_BRANCH "dev"
#define EDITOR_BUILD_TIMESTAMP "20260207212441"
#define EDITOR_GIT_DIRTY 1
